#' owrd_data_2_AWQMS
#' format data from OWRD into an AWQMS format
#'
#' This function takes data exported from OWRD using the owrd_data() function and formats for AWQMS. Only high quality,
#' published temperature data should be passed to this function as it doesn't do any QC checks, nor is it currently
#' setup for DO or other parameters.
#'
#' @param df dataframe to format into AWQMS
#' @param project project to put data into
#' @export
#' @return data frame of data formatted


owrd_AWQMS <- function(df, project = ""){


temp4ma <- df %>%
  mutate(Date = lubridate::mdy(record_date)) %>%
  group_by(station_nbr) %>%
  dplyr::mutate(row = dplyr::row_number(),
                d = runner(x = data.frame(dyMax_run = Result.Value,  datetime = Date),
                           k = "7 days",
                           lag = 0,
                           idx = Date,
                           f = function(x) list(x))) %>%
  dplyr::mutate(d = purrr::map(d, ~ .x %>%
                                 dplyr::summarise(ma.max7 = dplyr::case_when(length(dyMax_run) >= 6 ~  mean(dyMax_run),
                                                                             TRUE ~ NA_real_
                                 ),
                                 ana_startdate7 = min(datetime),
                                 ana_enddate7 =  max(datetime),
                                 act_enddate7 = max(datetime))
  ))%>%
  tidyr::unnest_wider(d) %>%
  dplyr::mutate(ma.max7 = ifelse(row < 7, NA, ma.max7)) %>%
  dplyr::select(-row)


sum.stats.temp.gather <- temp4ma %>%
  tidyr::gather(Result.Value,
                ma.max7, key = "stat", value = "result", na.rm = TRUE) %>%
  dplyr::select( station_nbr, Date, stat, result,  ana_startdate7,ana_enddate7,act_enddate7  ) %>%
  dplyr::arrange(station_nbr, Date) %>%
  dplyr::mutate(stat = ifelse(stat == "Result.Value", 'Wtemp_Max', stat))



sum.stats.temp.AWQMS <-sum.stats.temp.gather %>%
  dplyr::ungroup() %>%
  dplyr::transmute(CharID = "Temperature, water",
                   Result =  round(result, 1),
                   Unit = "deg C",
                   Method = "T-170.1",
                   RsltType = "Calculated",
                   Qualcd = 'Final',
                   StatisticalBasis = dplyr::case_when(stat == "ma.max7" ~"7DMADMax",
                                                       stat == "Wtemp_Max" ~ "Daily Maximum",
                                                       stat == "Wtemp" ~ "Daily Mean",
                                                       stat == "Wtemp_Min" ~ "Daily Minimum",
                                                       TRUE ~  "ERROR"),
                   RsltTimeBasis = ifelse(StatisticalBasis == "7DMADMax", "7 Day", "1 Day" ),
                   DEQ_RsltComment = ifelse(StatisticalBasis == "7DMADMax", "Generated by ORDEQ", "" ),
                   ActivityType = "FMC",
                   SiteID = station_nbr,
                   SmplColMthd = "ContinuousPrb",
                   SmplColEquip = "Probe/Sensor",
                   SmplDepth = "",
                   SmplDepthUnit = "",
                   SmplColEquipComment = "",
                   Samplers = "",
                   SmplEquipID = "Continuous Probe",
                   Project = project,
                   ActStartDate = Date,
                   ActStartTime = "0:00",
                   ActStartTimeZone = "PST",
                   ActEndDate =Date,
                   ActEndTime = "0:00",
                   ActEndTimeZone = "PST",
                   AnaStartDate = case_when(RsltTimeBasis == "1 Day" ~ format(Date, format="%Y-%m-%d"),
                                            RsltTimeBasis == "7 Day" ~ format(ana_startdate7, format="%Y-%m-%d")),
                   AnaStartTime = case_when(RsltTimeBasis == "1 Day" ~ format(Date, format="%H:%M:%S"),
                                            RsltTimeBasis == "7 Day" ~ format(ana_startdate7, format="%H:%M:%S")),
                   AnaStartTimeZone = "PST",
                   AnaEndDate = case_when(RsltTimeBasis == "1 Day" ~ format(Date, format="%Y-%m-%d"),
                                          RsltTimeBasis == "7 Day" ~ format(ana_enddate7, format="%Y-%m-%d")),
                   AnaEndTime = case_when(RsltTimeBasis == "1 Day" ~ format(Date, format="%H:%M:%S"),
                                          RsltTimeBasis == "7 Day" ~ format(ana_enddate7, format="%H:%M:%S")),
                   AnaEndTimeZone = "PST",
                   ActComment = "",
                   ActivityID = paste0(SiteID, ":", gsub("-","",ActStartDate), ":", ActivityType)) %>%
  dplyr::arrange(SiteID, ActStartDate)



return(sum.stats.temp.AWQMS)
}
